name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - clean_up_for_v1
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          brew install mpich zlib
          python -m pip install --upgrade pip
          pip install -e .[docs]

      - name: Clean and generate docs
        run: |
          rm -rf docs/pmmoto.*.rst docs/modules.rst docs/_build/html
          sphinx-apidoc -o docs/ src/pmmoto --force --module-first
          cd docs
          make html

      - name: List built docs
        run: |
          ls -lh docs/_build/html/genindex.html
          ls -lh docs/_build/html/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true # Ensures old files are removed
