name: Build and Release

on:
  push:
    tags:
      - "v*.*.*" # Trigger on tags like v0.1.5

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, macos]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show python and pip versions
        run: |
          python --version
          python -m pip --version
          python -m pip list

      - name: Install cibuildwheel and twine
        run: python -m pip install --upgrade pip "cibuildwheel>=2.8.0" twine

      - name: Build wheels
        env:
          CIBW_PLATFORM: ${{ matrix.platform }}
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload wheelhouse/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
