name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, macos, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel twine

      - name: Build wheels
        env:
          CIBW_PLATFORM: ${{ matrix.platform }}
          # Optional: limit Python versions with CIBW_SKIP or CIBW_BUILD
          # Example: CIBW_BUILD: "cp311-*"
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload wheelhouse/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
